CREATE TABLE IF NOT EXISTS users (
    id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    username VARCHAR(50) UNIQUE NOT NULL,
    password TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS workouts (
    id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    user INT NOT NULL
)